name: Fetch Weekly toto Data

on:
  schedule:
    # 毎週木曜日の日本時間 22:00（世界標準時 13:00）に自動実行
    - cron: '0 16 * * 4'
  workflow_dispatch: # 手動でいつでも実行できるようにするボタンを設置
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install beautifulsoup4

    - name: Run script
      env:
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      run: python fetch_toto.py

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.json
        git commit -m "Automated data update" || echo "No changes to commit"
        git push
